services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=budget_db
    volumes:
      - budget_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  api:
    build:
      context: .
      target: api # Désormais supporté par la version 3.8
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/budget_db
      - PORT=3001
    depends_on:
      - db
    restart: always

  web:
    build:
      context: .
      target: web
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/budget_db
      - API_URL=https://api-budgetapp.ricardomboukou.online
      - NEXT_PUBLIC_API_URL=https://api-budgetapp.ricardomboukou.online
      - AUTH_SECRET=your-super-secret-key-change-in-production
    depends_on:
      - api
      - db
    restart: always

volumes:
  budget_db_data:
